# Generated by Django 3.0.8 on 2020-09-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=20, unique=True)),
                ('co_regno', models.IntegerField(default='020')),
                ('co_city', models.CharField(max_length=20)),
                ('co_category', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Telecom', 'Telecom'), ('Insurance', 'Insurance'), ('Others', 'Others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('profile', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(choices=[('Java Developer', 'Java Developer'), ('Python Developer', 'Python Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Software Tester', 'Software Tester'), ('Others', 'Others')], max_length=20)),
                ('job_city', models.CharField(max_length=20)),
                ('tot_exp', models.IntegerField()),
                ('job_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Job')),
            ],
        ),
    ]
